[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc20-helpers/=lib/erc20-helpers/src/",
    "forge-std/=lib/forge-std/src/",
    "sparklend-v1-core/=lib/sparklend-v1-core/contracts"
]

[fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
